version: "3.8"
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      EXAMPLE_VAR: "example"
    command: ["gunicorn", "-c", "/opt/fraud_detection/gunicorn.conf.py", "fraud_detection.wsgi:application"]