# Generated by Django 5.1.5 on 2025-01-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='user_transaction',
        ),
    ]
